CREATE TABLE `sql12561279`.`Players`(
    `PlayerId` BIGINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    `PlayerName` VARCHAR(200) NOT NULL,
    `Password` VARCHAR(200) NOT NULL,
    `GamesWon` INT NOT NULL DEFAULT 0,
    `JoinedOn` DATETIME NOT NULL
) ENGINE = INNODB;